### ISSUE TITLE
When testing "ask", Max retries exceeded with WD

### ISSUE THREAD

**Issue by apetrov-msk** [primeqa/create-primeqa-app#6]
While submitting a request for question answering, with a configured WD retriever, getting a connection timeout exception.
In the same time testing with both curl command and PrimeQA for collection ID does not run into a connection issue.

**Comment by apetrov-msk** [comment]
For CP4D,  getting the following exception: 
 MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cpd-xyz.org', port=443): Max retries exceeded with url: /discovery/cpd-wd/instances/1638335259151122/api/v2/projects/b5bfbb0f-3eb1-4a67-a218-1b4b256d2e38/query?version=2020-08-30 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7da424a520>, 'Connection to cpd-xyz.org timed out. (connect timeout=60)'))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/opt/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/opt/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/venv/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/opt/venv/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/venv/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/opt/venv/lib/python3.9/site-packages/orchestrator/service/application.py", line 386, in ask
    documents = retrieve(
  File "/opt/venv/lib/python3.9/site-packages/orchestrator/retrievers/__init__.py", line 167, in retrieve
    documents = retrieve_for_discovery_retrievers(
  File "/opt/venv/lib/python3.9/site-packages/orchestrator/retrievers/discovery.py", line 183, in retrieve_for_discovery_retrievers
    for hit in retrieve(
  File "/opt/venv/lib/python3.9/site-packages/orchestrator/integrations/discovery/engine.py", line 53, in retrieve
    hits = WDS.query(
  File "/opt/venv/lib/python3.9/site-packages/ibm_watson/discovery_v2.py", line 1236, in query
    response = self.send(request, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/ibm_cloud_sdk_core/base_service.py", line 308, in send
    response = self.http_client.request(**request,
  File "/opt/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cpd-xyz.org', port=443): Max retries exceeded with url: /discovery/cpd-wd/instances/1638335259151122/api/v2/projects/b5bfbb0f-3eb1-4a67-a218-1b4b256d2e38/query?version=2020-08-30 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7da424a520>, 'Connection to cpd-xyz.org timed out. (connect timeout=60)'))

**Comment by apetrov-msk** [comment]
Here is the corresponding curl command for PrimeQA: 
Question answering: 
curl -X 'POST' 'http://localhost:50059/ask' -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "question": "What tax forms will I receive?",
  "retriever": {
    "retriever_id": "WatsonDiscovery"
  },
  "collection": {
    "collection_id": "c400817e-215d-6569-0000-01840aea36f7",
    "name": "W2 Collection"
  },
  "reader": {
    "reader_id": "ExtractiveReader"
  }
}'

**Comment by apetrov-msk** [comment]
Here is a curl command for the underlying WD request: 
curl -X POST --header "Content-Type:application/json" --data "{  \"collection_id\":\"c400817e-215d-6569-0000-01840aea36f7\", \"query\": \"text:What tax form will I receive?\" }" -H "Authorization: Bearer XYZ" "https://cpd-xyz.org/discovery/cpd-wd/instances/1638335259151122/api/v2/projects/b5bfbb0f-3eb1-4a67-a218-1b4b256d2e38/query?version=2020-08-30"

**Comment by apetrov-msk** [comment]
Here is a curl command for retrieving the collection id through PrimeQA, which works without connection timeout: 
curl -X 'GET' 'http://localhost:50059/retrievers/WatsonDiscovery/collections' -H 'accept: application/json'
And its output:
[{"name":"W2 Collection","collection_id":"c400817e-215d-6569-0000-01840aea36f7"}]

**Comment by maximek3** [comment]
I have a similar issue. 

I get this return message when submitting an equivalent command: `{"detail":{"code":"E5002","message":"Failed to establish connection."}}`

When I try to open http://localhost:50059/ask in my browser, I get this message: `{"detail":"Method Not Allowed"}`

**Comment by kpfadnis** [comment]
@apetrov-msk @maximek3 Are you still noticing connectivity issue with the curl and or via UI (Retrieval application)?

**Comment by maximek3** [comment]
No, by following the updated instructions for setting the `PUBLIC_IP` environment variable this no longer happens.

**Comment by kpfadnis** [comment]
Closing as resolved.
